edition = "2018"
unstable_features = true
max_width = 130
blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
condense_wildcard_suffixes = true
fn_single_line = true
#format_macro_matches = true
format_strings = true
merge_imports = true
overflow_delimited_expr = true
reorder_impl_items = true
#use_field_init_shothand = true
wrap_comments = true
#group_imports = "StdExternalCrate"
